### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'edge_embedding'    

### ISSUE THREAD

**Issue by ylli0** [AnomalyLLM/AnomalyLLM#3]
When I run the alignment.py, there is an error in the ./code/run_llama.py 
The code is 
```
output_get_emb = model(
            input_ids = input_ids_variable,
            output_hidden_states=True,
            edge_embedding=new_edge_embs,
            past_key_values=expanded_past_key_values,
            add_example=add_example,
        )
```
the mode here is an object of DyGLlamaForCausalLM, the forward function in its base class transformers.models.llama.LlamaPreTrainedModel. The forward function is defined as 
```
@add_start_docstrings_to_model_forward(LLAMA_INPUTS_DOCSTRING)
@replace_return_docstrings(output_type=CausalLMOutputWithPast, config_class=_CONFIG_FOR_DOC)
def forward(
     self,
     input_ids: torch.LongTensor = None,
     attention_mask: Optional[torch.Tensor] = None,
     position_ids: Optional[torch.LongTensor] = None,
     past_key_values: Optional[Union[Cache, List[torch.FloatTensor]]] = None,
     inputs_embeds: Optional[torch.FloatTensor] = None,
     labels: Optional[torch.LongTensor] = None,
     use_cache: Optional[bool] = None,
     output_attentions: Optional[bool] = None,
     output_hidden_states: Optional[bool] = None,
      return_dict: Optional[bool] = None,
      cache_position: Optional[torch.LongTensor] = None,
    ) -> Union[Tuple, CausalLMOutputWithPast]:
```
we can see that the edge_embedding and add_example are not in the input params of forward function. I think it may be the reason for the error. The traceback is as follows: 
```
Traceback (most recent call last):
  File "/opt/conda/envs/pyg/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/pyg/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.10.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/workspace/code/AnomalyLLM/alignment.py", line 63, in <module>
    setting_obj.run(step)
  File "/workspace/code/AnomalyLLM/codes/Settings.py", line 12, in run
    learned_result = self.method.run(step)
  File "/workspace/code/AnomalyLLM/codes/AnomalyLLM.py", line 532, in run
    self.alignment(self.max_epoch)
  File "/workspace/code/AnomalyLLM/codes/AnomalyLLM.py", line 425, in alignment
    output, anchor_representation, positive_representation, negative_representation = self.forward(
  File "/workspace/code/AnomalyLLM/codes/AnomalyLLM.py", line 168, in forward
    llama_normal_edge = run_llama(llama_model, args_llama, result_list, "few-shot", True)
  File "/workspace/code/AnomalyLLM/codes/run_llama.py", line 138, in run_llama
    output_get_emb = model(
  File "/opt/conda/envs/pyg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'edge_embedding'
```

**Comment by XiaoWenyilin** [comment]
As you wrote at the top, the mode here is an object of DyGLlamaForCausalLM. According to MetaLlama.py
```
def __init__(self, config, edge_embedding: Optional[List[torch.Tensor]] = None, add_example: Optional[bool] = None):
    super(LlamaForCausalLM, self).__init__(config)
    self.edge_emb = edge_embedding
    self.add_example = add_example
    self.model = DyGLlamaModel(config, edge_embedding, add_example)
    self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
    # Initialize weights and apply final processing
    self.post_init()
```
the forward function we need is in DyGLlamaModel, so I fix it by
```
    output_get_emb = model.model( ...)
```
Hope this helps you. :smile:
