### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by oyq-star** [AnomalyLLM/AnomalyLLM#7]
When I run the alignment.py, there is an error in the `./model/MetaLlama.py`
The code is 
```
      start_token = 8111
      for cur_input_ids, cur_input_embeds in zip(input_ids, inputs_embeds):
          cur_edge_idx = 0
          cur_new_input_embeds=None
          graph_start_tokens = torch.where(cur_input_ids == start_token)[0]
          for graph_start_token_pos in graph_start_tokens:
              cur_graph_features = edge_embedding[cur_input][cur_edge_idx].float() #1*4096
              cur_new_input_embeds = torch.cat((cur_input_embeds[:graph_start_token_pos],
                                                cur_graph_features,
                                                cur_input_embeds[graph_start_token_pos + 1:]),
                                               dim=0)
              cur_edge_idx += 1
          if cur_new_input_embeds!=None:
              new_input_embeds.append(cur_new_input_embeds)
              cur_input += 1
      inputs_embeds = torch.stack(new_input_embeds, dim=0).to(torch.float16)
```
we get the input_ids as followings:
```
        if label == "few-shot":
        qs = "As an AI trained in the few-shot learning approach, I have been provided with examples of both normal and anomaly edges. The anomalies are identified as Contextual Dissimilarity Anomalies, where we first utilize node2vec to obtain the representation of each node in the graph, and connect the pairs of nodes with the maximum Euclidean distance as anomaly edges. These examples serve as a reference for detecting similar patterns in new edges. Please note the following examples and their labels, indicating whether they are normal or anomaly: Example 1: <vector> Label: Normal  Example 2: <vector> Label: Anomaly Example 3: <vector> Label: Normal Example 4: <vector> Label: Normal Example 5: <vector> Label: Anomaly Example 6: <vector> Label:Anomaly Example 7: <vector> Label: Anomaly Example 8: <vector> Label: Anomaly Example 9: <vector> Label: Normal Example 10: <vector> Label: Anomaly (Note: All the above examples are anomaly and represent the same type of anomaly.) Based on the pattern in the examples and samples provided, classify the sentiment of the following new edge. If the new edge is similar to the example edges, it should be considered anomaly. If it is dissimilar, it should be considered normal. New Example: <vector> Label:"

        conv_mode = "vicuna_v1_1"

        if args.conv_mode is not None and conv_mode != args.conv_mode:
            print('[WARNING] the auto inferred conversation mode is {}, while `--conv-mode` is {}, using {}'.format(
                conv_mode, args.conv_mode, args.conv_mode))
        else:
            args.conv_mode = conv_mode

        conv = conv_templates[args.conv_mode].copy()
        conv.append_message(conv.roles[0], qs)
        conv.append_message(conv.roles[1], None)
        prompt = conv.get_prompt()
        input_ids = tokenizer([prompt]).input_ids

        # print(input_ids)

        input_ids = torch.as_tensor(input_ids).cuda()

        # 计算当前切片的结束索引，确保不会超出列表的长度
        end_index = min(i + batch_size, len(all_edge_1))
        # 从all_edge_1中取出当前的切片，并将其转换为float类型和移动到CUDA设备0上
        current_slice = [x.float().cuda(0) for x in all_edge_1[i:end_index]]
        new_edge_embs = []
        for ind in range(len(current_slice)):
            updated_emb = edge_embs.copy()
            updated_emb.append(current_slice[ind])
            new_edge_embs.append(updated_emb)

        # Calculate the actual size of the current batch
        current_batch_size = end_index - i

        # print(input_ids.shape)

        input_ids = input_ids.repeat(current_batch_size, 1)

        input_ids_variable = input_ids[:, 308:317]
```
I want to know why `start_token = 8111` and why ` input_ids_variable = input_ids[:, 308:317]`, because by this way `graph_start_tokens` is empty . The traceback is as follows:
```
Traceback (most recent call last):
  File "/codes/graph_LLM/AnomalyLLM-main2/alignment.py", line 61, in <module>
    setting_obj.run(step)
  File "/codes/graph_LLM/AnomalyLLM-main2/codes/Settings.py", line 12, in run
    learned_result = self.method.run(step)
  File "/codes/graph_LLM/AnomalyLLM-main2/codes/AnomalyLLM.py", line 543, in run
    self.alignment(self.max_epoch)
  File "/codes/graph_LLM/AnomalyLLM-main2/codes/AnomalyLLM.py", line 436, in alignment
    output, anchor_representation, positive_representation, negative_representation = self.forward(
  File "/codes/graph_LLM/AnomalyLLM-main2/codes/AnomalyLLM.py", line 179, in forward
    llama_normal_edge = run_llama(llama_model, args_llama, result_list, "few-shot", True)
  File "/codes/graph_LLM/AnomalyLLM-main2/codes/run_llama.py", line 123, in run_llama
    output_get_emb = model.model(
  File "/opt/conda/envs/pyg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/codes/graph_LLM/AnomalyLLM-main2/codes/model/MetaLlama.py", line 78, in forward
    inputs_embeds = torch.stack(new_input_embeds, dim=0).to(torch.float16)
RuntimeError: stack expects a non-empty TensorList
```

**Comment by Xenorian** [comment]
Here is seem to be the procedure of insert the embedding of the edge by replacing the embedding of < vector > into real edge embeddings.  so I fix it by change 8111 into the id of 'vector'.

**Comment by LPBer** [comment]
Hello! Why do we need to slice input_ids[:, 308:317]? What is the meaning of the original prompt?

**Comment by zujia-w** [comment]
Hello, have you obtained the dataset and all the codes? Can you upload them?
